spring:
  application:
    name: qr-poc

  datasource:
    url: jdbc:postgresql://localhost:5432/pocdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081